### PR TITLE
:art: Restructure container files and materials

### PR DESCRIPTION
**Pull request by kks32**
- Move containers to a separate folder
- Rename container as vector to be more specific
- Rename `material` folder to `materials` to be consistent with other folders

### CODE REVIEW

**Review by cbgeo — APPROVED** [review]

**Review by bodhinandach — APPROVED** [review]
I am okay, but why you change the name from Container->Vector? Any specific thoughts? Are you planning to generate a Matrix container too?

**Comment by bodhinandach** [comment]
@kks32 shall we wait for #562 to merge first before merging this?

**Comment by kks32** [comment]
@bodhinandach Map is technically a container, so I'm being more specific with renaming it to a Vector. We are likely to have other containers, and since we mirror std::vector functions it's easier to call it a Vector than a more generic container. 

I'll wait for #562

**Comment by bodhinandach** [comment]
I am good. Thanks Krishna! We can merge now

**Pull request merged**
