### PR TITLE
[Materials] MohrCoulomb derivatives of R

### PR DESCRIPTION
**Pull request by ezrayst**
Not sure about the derivatives highlighted in this PR. 

If @tianchiTJ is OK, I would make the test cases too. Below is my document on the derivatives.

image

### CODE REVIEW

**Comment by tianchiTJ** [comment]
I think there should be a negative sign in A.42, and others should be good in my opinion.

**Comment by ezrayst** [comment]
That is another thing we need to discuss. I use sin convention for Lode Angle and that's why there is no negative. But you agree in the pull request? I will make the test cases then

**Comment by tianchiTJ** [comment]
You equations are right, but the rho=sqrt(2J2), so I think the original code should be correct

**Comment by ezrayst** [comment]
I see. Understood thanks!

**Pull request closed without merging**
