### PR TITLE
Remove fedora command in partio installation commands

### PR DESCRIPTION
**Pull request by ezrayst**
**Describe the PR**
Just cleaning up installation commands to exclude one fedora installation line in ubuntu installation guide.

### CODE REVIEW

**Review by bodhinandach — COMMENTED** [review]
Hmmm... I think we need those libraries though to run Partio?

**Comment by ezrayst** [comment]
Not in the this section

**Review by kks32 — COMMENTED** [review]
We need these libraries, and this section is not under ubuntu, This is a separate section for compiling with Partio. This has the same section hierarchy as Fedora / Ubuntu.

**Comment by ezrayst** [comment]
Yes, but we have the libraries in the dependencies before right - like the line for Fedora? And if this is for both Ubuntu and Fedora, these lines cannot be used for Ubuntu anyways.

**Comment by kks32** [comment]
If someone wants to install partio these are dependencies, so it's good to have them there. Also, our recommended OS is Fedora, so all installation instructions are with respect to Fedora.

**Comment by ezrayst** [comment]
But isn't it a duplicate of what you have in the dependency installation?

**Comment by bodhinandach** [comment]
@kks32 One question: these dependencies are not available in Ubuntu: `libnsl freeglut freeglut-devel`. Do we need anything to install partio in Ubuntu?

**Review by bodhinandach — APPROVED** [review]
I checked that the installation of Partio in Ubuntu does not require the specified libraries/dependencies. I am okay to remove them.

**Review by kks32 — APPROVED** [review]

**Pull request merged**
