### PR TITLE
Change state vars to 25

### PR DESCRIPTION
**Pull request by ezrayst**
Since `norsand` has 21 state variables, I think we need to increase this number to 25.

### CODE REVIEW

**Comment by kks32** [comment]
Are storing state variables like `p` and `q` necessary, could it not be easily computed from the stresses? Could you please explain the reasoning behind storing these state variables?

**Review by kks32 — CHANGES_REQUESTED** [review]
Is this change necessary if you can drop `p` and `q` from state variables in NorSand as they can be computed easily from the stresses?

**Comment by ezrayst** [comment]
If the choice is to save them as state variables or to compute them, I rather do the former because we will end up passing or computing them a lot (we have different functions that use them). I would make a subroutine to reduce repetition in `norsand` for sure. 

Any thoughts why 25 is not favorable compared to 20?

**Comment by kks32** [comment]
You need to compute mean p and q already at each step so I don't understand why you need to store it. We can avoid increasing the number of state variables, which is a far bigger impact than computing and doing an addition operation. 20 is already a lot and with millions of particles this will be an unnecessary communication overhead. If we can't avoid it, it makes sense, but we can avoid it, so why try to increase it unnecessarily?

**Comment by ezrayst** [comment]
I will try to refactor the constitutive model then. I should be able to pass them in different functions. Maybe that's a better solution than to increase the number of state variables.

**Comment by kks32** [comment]
Closing this PR as NorSand can be refactored to not need an increase in the number of state variables.

**Pull request closed without merging**
